name = "gtfs_rt_nyct"
version = "0.1.0"

links = [
  { title = "GTFS-RT Specification", href = "https://gtfs.org/documentation/realtime/reference/" },
  { title = "MTA NYCT Developer Resources", href = "https://www.mta.info/developers" },
  { title = "GTFS-RT Protobuf Schema", href = "https://github.com/google/transit/blob/master/gtfs-realtime/proto/gtfs-realtime.proto" },
  { title = "MTA NYCT GTFS-RT Extensions Protobuf Schema", href = "https://raw.githubusercontent.com/OneBusAway/onebusaway-gtfs-realtime-api/master/src/main/proto/com/google/transit/realtime/gtfs-realtime-NYCT.proto" },
]
description = "NYCT-specific GTFS-RT bindings and decoders for Gleam!"
licences = ["Apache-2.0"]
repository = { type = "github", user = "gavinmorrow", repo = "gtfs-rt-nyct-gleam" }

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
protobin = ">= 2.0.0 and < 3.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
simplifile = ">= 2.3.0 and < 3.0.0"
gleamy_bench = ">= 0.6.0 and < 0.7.0"
